logging:
  level:
    com.paul: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ONOS?serverTimeZone=UTC
    username: root
    password: 1014352987
# 开启Mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

basicAuthentication:
  username: onos
  password: rocks

requestURL:
  ipAddress:
    ip: 172.20.249.201
  version: onos/v1
  port: 8181
  host: http://${requestURL.ipAddress.ip}:${requestURL.port}/${requestURL.version}/hosts
  link: http://${requestURL.ipAddress.ip}:${requestURL.port}/${requestURL.version}/links
  device: http://${requestURL.ipAddress.ip}:${requestURL.port}/${requestURL.version}/devices
  flow: http://${requestURL.ipAddress.ip}:${requestURL.port}/${requestURL.version}/flows


server:
  port: 8081

jwt:
  # jwt签名加密时使用的秘钥
  secret-key: paul


